### PR TITLE
Update Composer dependencies to OJS 3.1

### PR DESCRIPTION
**Pull request by israelcefrin**
Added lines to install composer and run update to _paypal_ and _citationStyleLanguage_ plugins. 
Lines were copied from: [OJS Documentation in Github](https://github.com/pkp/ojs/#documentation).

### CODE REVIEW

**Comment by asmecher** [comment]
Merged, thanks! I'll give this a crack and see what else is needed, if anything (e.g. I forget how I was managing branches on this repo)

**Comment by asmecher** [comment]
Yes, it looks like node tools are needed; I'll drop a link here to the commit once it's added.

**Comment by asmecher** [comment]
See https://github.com/pkp/vagrant/commit/c82f710f1a7cbe803e59e296aabcaed11852ba32. (Without this, the submission lists won't work.)

**Comment by israelcefrin** [comment]
Great!!! 
I will clone again to test.

**Pull request merged**
